#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  4 22:42:54 2018

@author: aadi
"""
# NewtonMehodSqr_root program-------

number = float(input('Enter ther number for squr root : '))

#w = int(number/2)
iter = number+1
p = iter
def sqroot(z,m):#z=4,m=5
    sq = m - (((m**2) - z)/(2*m))
    return sq       
for j in range(0,int(number+1000)):
   # print('p:',p)
    u = p
    p = sqroot(number,p)
   # print('n:',n,'p:',p)
    if(p == u):
        break

print(p)